#设置端口号
server:
  port: 8888
# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#logback日志打印，
logging:
  config: classpath:logback.xml
# mybatis config
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.example.demo.entity
  global-config:
    db-config:
      id-type: auto

